services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - vol-pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin

  app:
    image: docker_homework:v001
    depends_on:
      - db
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=5432
      - PG_DB=ny_taxi
      - GREEN_TRIP_URL=https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet
      - TAXI_ZONE_URL=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
      - DATA_DIR=/data
    volumes:
      - vol-appdata:/data
    command: ["--pg-host", "postgres", "--pg-user", "postgres", "--pg-password", "postgres", "--pg-port", "5432", "--pg-db", "ny_taxi"]

volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmin_data:
    name: vol-pgadmin_data
  vol-appdata:
    name: vol-appdata